/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.busmania;

import java.awt.Color;
import static java.awt.Color.red;
import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Faisal
 */
public final class TicketBooking extends javax.swing.JFrame {

    /**
     * Creates new form TicketBooking
     */
    public TicketBooking() {
        initComponents();
        ScaleImage1();
        ScaleImage2();
        ScaleImage3();
    }
    public void ScaleImage1(){
        ImageIcon ic;
        ic = new ImageIcon("D:\\Java\\BusMania\\src\\img\\steer.png");
        Image im = ic.getImage();
        Image imScale = im.getScaledInstance(Steer.getWidth(),Steer.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledicon =new ImageIcon(imScale);
        Steer.setIcon(scaledicon);
    }
    public void ScaleImage2(){
        ImageIcon ic;
        ic = new ImageIcon("D:\\Java\\BusMania\\src\\img\\SeatBack.jpg");
        Image im = ic.getImage();
        Image imScale = im.getScaledInstance(SeatB.getWidth(),SeatB.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledicon =new ImageIcon(imScale);
        SeatB.setIcon(scaledicon);
    }
    public void ScaleImage3(){
        ImageIcon ic;
        ic = new ImageIcon("D:\\Java\\BusMania\\src\\img\\back.jpg");
        Image im = ic.getImage();
        Image imScale = im.getScaledInstance(Background.getWidth(),Background.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledicon =new ImageIcon(imScale);
        Background.setIcon(scaledicon);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        From = new javax.swing.JComboBox<>();
        To = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Search = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        A1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        Steer = new javax.swing.JLabel();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        SeatB = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        flevel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tlevel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dlevel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        NSeat = new javax.swing.JTextField();
        dateee = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel18 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        From.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Noakhali", "Dhaka", "Chittagong", "CoxBazar", "Cumilla", "Feni", " " }));
        From.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromActionPerformed(evt);
            }
        });
        getContentPane().add(From, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 45, 140, 30));

        To.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Dhaka", "Cumilla", "Chittagong", "Feni", "CoxBazar", "Noakhali" }));
        To.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToActionPerformed(evt);
            }
        });
        getContentPane().add(To, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 85, 140, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("FROM ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 46, 40, 20));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("TO ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 86, 20, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("DATE ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 126, 40, 20));

        Search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Search.setText("FIND");
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 172, 80, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("NAME :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 36, 40, 20));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 32, 160, 30));
        getContentPane().add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 140, 30));

        A1.setBackground(new java.awt.Color(0, 255, 0));
        A1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        A1.setText("A1");
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        getContentPane().add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 100, 50, 30));

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setText("A2");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 100, 50, 30));

        jButton5.setBackground(new java.awt.Color(0, 255, 0));
        jButton5.setText("A4");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 100, 50, 30));

        jButton6.setBackground(new java.awt.Color(0, 255, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton6.setText("A3");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 100, 50, 30));

        jButton3.setBackground(new java.awt.Color(0, 255, 0));
        jButton3.setText("B2");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 140, 50, 30));

        jButton7.setBackground(new java.awt.Color(0, 255, 0));
        jButton7.setText("B4");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 140, 50, 30));

        jButton8.setBackground(new java.awt.Color(0, 255, 0));
        jButton8.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton8.setText("B3");
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 140, 50, 30));

        jButton4.setBackground(new java.awt.Color(0, 255, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton4.setText("B1");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 140, 50, 30));

        jButton9.setBackground(new java.awt.Color(0, 255, 0));
        jButton9.setText("C2");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 180, 50, 30));

        jButton10.setBackground(new java.awt.Color(0, 255, 0));
        jButton10.setText("C4");
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 180, 50, 30));

        jButton11.setBackground(new java.awt.Color(0, 255, 0));
        jButton11.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton11.setText("C3");
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 180, 50, 30));

        jButton12.setBackground(new java.awt.Color(0, 255, 0));
        jButton12.setText("D2");
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 220, 50, 30));

        jButton13.setBackground(new java.awt.Color(0, 255, 0));
        jButton13.setText("D4");
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 220, 50, 30));

        jButton14.setBackground(new java.awt.Color(0, 255, 0));
        jButton14.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton14.setText("D3");
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 220, 50, 30));

        jButton15.setBackground(new java.awt.Color(0, 255, 0));
        jButton15.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton15.setText("D1");
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 220, 50, 30));

        jButton16.setBackground(new java.awt.Color(0, 255, 0));
        jButton16.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton16.setText("C1");
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 180, 50, 30));

        jButton17.setBackground(new java.awt.Color(0, 255, 0));
        jButton17.setText("E2");
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 260, 50, 30));

        jButton18.setBackground(new java.awt.Color(0, 255, 0));
        jButton18.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton18.setText("G1");
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 340, 50, 30));

        jButton19.setBackground(new java.awt.Color(0, 255, 0));
        jButton19.setText("E4");
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 260, 50, 30));

        jButton20.setBackground(new java.awt.Color(0, 255, 0));
        jButton20.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton20.setText("E3");
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 260, 50, 30));

        jButton21.setBackground(new java.awt.Color(0, 255, 0));
        jButton21.setText("F2");
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 300, 50, 30));

        jButton22.setBackground(new java.awt.Color(0, 255, 0));
        jButton22.setText("F4");
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 300, 50, 30));

        jButton23.setBackground(new java.awt.Color(0, 255, 0));
        jButton23.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton23.setText("F3");
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 300, 50, 30));

        jButton24.setBackground(new java.awt.Color(0, 255, 0));
        jButton24.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton24.setText("F1");
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 300, 50, 30));

        jButton25.setBackground(new java.awt.Color(0, 255, 0));
        jButton25.setText("G2");
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 340, 50, 30));

        jButton26.setBackground(new java.awt.Color(0, 255, 0));
        jButton26.setText("G4");
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 340, 50, 30));

        jButton27.setBackground(new java.awt.Color(0, 255, 0));
        jButton27.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton27.setText("G3");
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 340, 50, 30));

        jButton28.setBackground(new java.awt.Color(0, 255, 0));
        jButton28.setText("H2");
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 380, 50, 30));

        jButton29.setBackground(new java.awt.Color(0, 255, 0));
        jButton29.setText("H4");
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 380, 50, 30));

        jButton30.setBackground(new java.awt.Color(0, 255, 0));
        jButton30.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton30.setText("H3");
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 380, 50, 30));

        jButton31.setBackground(new java.awt.Color(0, 255, 0));
        jButton31.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton31.setText("E1");
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 260, 50, 30));

        jButton32.setBackground(new java.awt.Color(0, 255, 0));
        jButton32.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton32.setText("H1");
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 380, 50, 30));

        jButton33.setBackground(new java.awt.Color(0, 255, 0));
        jButton33.setText("I2");
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 420, 50, 30));

        jButton34.setBackground(new java.awt.Color(0, 255, 0));
        jButton34.setText("I4");
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 420, 50, 30));

        jButton35.setBackground(new java.awt.Color(0, 255, 0));
        jButton35.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton35.setText("I3");
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 420, 50, 30));

        jButton36.setBackground(new java.awt.Color(0, 255, 0));
        jButton36.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton36.setText("I1");
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 420, 50, 30));

        jButton37.setBackground(new java.awt.Color(0, 255, 0));
        jButton37.setText("J4");
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(885, 460, 50, 30));

        jButton38.setBackground(new java.awt.Color(0, 255, 0));
        jButton38.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton38.setText("J3");
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 460, 50, 30));

        jButton39.setBackground(new java.awt.Color(0, 255, 0));
        jButton39.setFont(new java.awt.Font("Segoe UI Symbol", 0, 12)); // NOI18N
        jButton39.setText("J1");
        getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 460, 50, 30));

        jButton40.setBackground(new java.awt.Color(0, 255, 0));
        jButton40.setText("J2");
        getContentPane().add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 460, 50, 30));
        getContentPane().add(Steer, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 44, 40, 40));

        jButton41.setBackground(new java.awt.Color(0, 255, 0));
        getContentPane().add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 40, 30, 20));

        jButton42.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 70, 30, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText(":    Available");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 36, 100, 20));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText(":    Booked");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 66, 100, 20));

        SeatB.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(SeatB, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 230, 480));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("CONTACT :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 36, 60, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("FROM :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 40, 20));
        getContentPane().add(flevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 120, 20));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("TO :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 66, 30, 20));
        getContentPane().add(tlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 130, 20));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("BUSNAME :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 96, 70, 20));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 140, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("DATE :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(486, 96, 40, 20));
        getContentPane().add(dlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 120, 20));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("NO OF SEAT :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 130, 80, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("TOTAL PRICE :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 160, 80, 20));
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 60, 20));
        getContentPane().add(NSeat, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 132, 70, 20));
        getContentPane().add(dateee, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 98, 140, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("RESET");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 203, 80, 20));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("PRICE :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 156, 40, 20));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 156, 80, 20));

        jButton43.setBackground(new java.awt.Color(0, 0, 0));
        jButton43.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton43.setForeground(new java.awt.Color(255, 255, 255));
        jButton43.setText("BOOK");
        getContentPane().add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 203, 80, 20));

        jButton44.setBackground(new java.awt.Color(0, 0, 0));
        jButton44.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton44.setForeground(new java.awt.Color(255, 255, 255));
        jButton44.setText("PAY");
        getContentPane().add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(542, 203, 80, 20));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Bus Name", "Ticket Fare", "Departure Time", "Arrival Time"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 710, 260));

        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 490, 230));

        jDateChooser2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser2PropertyChange(evt);
            }
        });
        getContentPane().add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 122, 140, 30));

        jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 220, 230));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 950, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromActionPerformed
         // TODO add your handling code here:
         String SelectedValue=From.getSelectedItem().toString();
         flevel.setText(SelectedValue);
    }//GEN-LAST:event_FromActionPerformed

    private void ToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToActionPerformed
        // TODO add your handling code here:
        String SelectedValue=To.getSelectedItem().toString();
         tlevel.setText(SelectedValue);
    }//GEN-LAST:event_ToActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        if(flevel.getText().isEmpty())JOptionPane.showMessageDialog(rootPane,"Select your starting place");
        else if(tlevel.getText().isEmpty())JOptionPane.showMessageDialog(rootPane,"Select your destination place");
        else if(name.getText().isEmpty()||contact.getText().isEmpty())JOptionPane.showMessageDialog(rootPane,"Fill up the text fields");
        else if(A1.getBackground()==red) JOptionPane.showMessageDialog(rootPane,"Seat Booked");
        else A1.setBackground(Color.yellow);
    }//GEN-LAST:event_A1ActionPerformed

    private void jDateChooser2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser2PropertyChange
        // TODO add your handling code here:
        if("date".equals(evt.getPropertyName())){
            Date date= jDateChooser2.getDateEditor().getDate();
            SimpleDateFormat sf = new SimpleDateFormat("dd/MM/yyyy");
            String mydate = sf.format(date);
            dateee.setText(mydate);
        }
        else{
            dateee.setText(null);
        }
    }//GEN-LAST:event_jDateChooser2PropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TicketBooking().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JLabel Background;
    private javax.swing.JComboBox<String> From;
    private javax.swing.JTextField NSeat;
    private javax.swing.JButton Search;
    private javax.swing.JLabel SeatB;
    private javax.swing.JLabel Steer;
    private javax.swing.JComboBox<String> To;
    private javax.swing.JTextField contact;
    private javax.swing.JTextField dateee;
    private javax.swing.JLabel dlevel;
    private javax.swing.JLabel flevel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JLabel tlevel;
    // End of variables declaration//GEN-END:variables
}
