
import java.awt.Dimension;
import java.awt.Image;
import javax.swing.ImageIcon;

public class Developer_Info extends javax.swing.JFrame {

    public Developer_Info() {
        initComponents();

        setSize(700, 500);
        //imgMahadi.setPreferredSize(new Dimension(700, 500));
        //scaleImageBg();
        scaleImageMahadi();
        scaleImageJabed();
        scaleImageAhnaf();
        scaleImageFaisal();
        scaleImageBackground();
        
        setResizable(false);
    }

    public void scaleImageBackground() {
        ImageIcon bg = new ImageIcon("D:\\Java\\BusMania\\src\\img\\back.jpg");
        Image img = bg.getImage();
        Image imgScale = img.getScaledInstance(imgBackground.getWidth(), imgBackground.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        imgBackground.setIcon(scaledIcon);
    }

    public void scaleImageMahadi() {
        ImageIcon mahadi = new ImageIcon("D:\\Java\\BusMania\\src\\img\\mahadi.jpg");
        Image img = mahadi.getImage();
        Image imgScale = img.getScaledInstance(imgMahadi.getWidth(), imgMahadi.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        imgMahadi.setIcon(scaledIcon);
    }

    public void scaleImageJabed() {
        ImageIcon jabed = new ImageIcon("D:\\Java\\BusMania\\src\\img\\jabed.jpeg");
        Image img = jabed.getImage();
        Image imgScale = img.getScaledInstance(imgJabed.getWidth(), imgJabed.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        imgJabed.setIcon(scaledIcon);
    }

    public void scaleImageAhnaf() {
        ImageIcon ahnaf = new ImageIcon("D:\\Java\\BusMania\\src\\img\\Ahnaf .jpg");
        Image img = ahnaf.getImage();
        Image imgScale = img.getScaledInstance(imgAhnaf.getWidth(), imgAhnaf.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        imgAhnaf.setIcon(scaledIcon);
    }

    public void scaleImageFaisal() {
        ImageIcon faisal = new ImageIcon("D:\\Java\\BusMania\\src\\img\\Faisal.jpg");
        Image img = faisal.getImage();
        Image imgScale = img.getScaledInstance(imgFaisal.getWidth(), imgFaisal.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imgScale);
        imgFaisal.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        dInfo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imgMahadi = new javax.swing.JLabel();
        imgJabed = new javax.swing.JLabel();
        imgFaisal = new javax.swing.JLabel();
        imgAhnaf = new javax.swing.JLabel();
        buttonExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        imgBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        backButton.setBackground(new java.awt.Color(153, 255, 0));
        backButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(28, 28, 80, 31);

        dInfo.setBackground(new java.awt.Color(255, 255, 255));
        dInfo.setFont(new java.awt.Font("Okinawa", 1, 36)); // NOI18N
        dInfo.setForeground(new java.awt.Color(88, 0, 75));
        dInfo.setText("DEVELOPER INFO");
        getContentPane().add(dInfo);
        dInfo.setBounds(190, 20, 330, 47);

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("version 1.0");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 440, 110, 17);

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("All Right Reserved");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(510, 440, 170, 17);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel7.setText("Bus Reservation System");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(210, 70, 290, 40);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Presented By");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 120, 130, 22);
        getContentPane().add(imgMahadi);
        imgMahadi.setBounds(550, 170, 100, 100);
        getContentPane().add(imgJabed);
        imgJabed.setBounds(380, 170, 100, 100);
        getContentPane().add(imgFaisal);
        imgFaisal.setBounds(210, 170, 100, 100);
        getContentPane().add(imgAhnaf);
        imgAhnaf.setBounds(40, 170, 100, 100);

        buttonExit.setBackground(new java.awt.Color(153, 255, 0));
        buttonExit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        buttonExit.setText("Exit");
        getContentPane().add(buttonExit);
        buttonExit.setBounds(575, 30, 80, 31);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Md. Mahadi Hasan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 290, 130, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Chowdhury");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 310, 90, 17);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Session: 2018-19");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(540, 360, 150, 17);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Roll: ASH1901005M");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(540, 340, 150, 17);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Md. Ahnaf Muttaqi");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 290, 130, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Roll: ASH1901041M");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(20, 340, 150, 17);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Session: 2018-19");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 360, 150, 17);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Md. Faisal Ahammed");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(190, 290, 150, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Roll: ASH1901047M");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(190, 340, 150, 17);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Session: 2018-19");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(190, 360, 150, 17);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText(" Jabed Kaium");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(380, 290, 100, 20);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Roll: ASH1901032M");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(370, 340, 150, 17);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Session: 2018-19");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(370, 360, 150, 17);
        getContentPane().add(imgBackground);
        imgBackground.setBounds(0, 0, 700, 500);

        setSize(new java.awt.Dimension(714, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        User_Login lg = new User_Login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Developer_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Developer_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Developer_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Developer_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Developer_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton buttonExit;
    private javax.swing.JLabel dInfo;
    private javax.swing.JLabel imgAhnaf;
    private javax.swing.JLabel imgBackground;
    private javax.swing.JLabel imgFaisal;
    private javax.swing.JLabel imgJabed;
    private javax.swing.JLabel imgMahadi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
