
import java.sql.*;
import java.awt.Image;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public final class Payment extends javax.swing.JFrame {

    String url = "jdbc:mysql://localhost:3306/busmania";
    String username = "root";
    String pass = "admin";
    Connection con;
    Statement stmt;
    int Nseat = 0, prevSeats = 0;
    String total, name, contact, from, to, date, atime, dtime, seat, busname, USERID;

    public Payment() {
        initComponents();
        ScaleImage1();
        ScaleImage2();
        setResizable(false);
    }

    public void ScaleImage1() {
        ImageIcon ic;
        ic = new ImageIcon("D:\\Java\\BusMania\\src\\img\\Light.jpg");
        Image im = ic.getImage();
        Image imScale = im.getScaledInstance(Light_Back.getWidth(), Light_Back.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledicon = new ImageIcon(imScale);
        Light_Back.setIcon(scaledicon);
    }

    public void ScaleImage2() {
        ImageIcon ic;
        ic = new ImageIcon("D:\\Java\\BusMania\\src\\img\\bkash payment.png");
        Image im = ic.getImage();
        Image imScale = im.getScaledInstance(Bkash_Back.getWidth(), Bkash_Back.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledicon = new ImageIcon(imScale);
        Bkash_Back.setIcon(scaledicon);
    }

    public Payment(String pname, String pcontact, String selectedFrom, String selectedTo, String selectedDate, String selectedTime, String selectedSeat, int Ns, String total_price, String bs, String Userid, String Atime) {
        initComponents();
        USERID = Userid;
        Nseat = Ns;
        total = total_price;
        name = pname;
        contact = pcontact;
        from = selectedFrom;
        to = selectedTo;
        date = selectedDate;
        dtime = selectedTime;
        atime = Atime;
        seat = selectedSeat;
        busname = bs;
        Show.setText("Great,That's " + total + "/- ");
        ScaleImage1();
        ScaleImage2();
        Setup_Database_Connection();
    }

    public void Setup_Database_Connection() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(url, username, pass); //2
            stmt = (Statement) con.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Database Error!", 0);
        }
    }

    public boolean userExists(String USERID, String busname) {
        boolean ok = false;
        try {
            String query = "SELECT * FROM my_booking WHERE user = '" + USERID + "' AND bus = '" + busname + "';";
            ResultSet rset = stmt.executeQuery(query);
            if (rset.next()) {
                ok = true;
                prevSeats = Integer.valueOf(rset.getString("seatBooked"));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e, "Database Error!", 0);
        }
        return ok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AC = new javax.swing.JLabel();
        Pass = new javax.swing.JLabel();
        amount = new javax.swing.JLabel();
        Acc = new javax.swing.JTextField();
        tk = new javax.swing.JTextField();
        pword = new javax.swing.JPasswordField();
        Light_Back = new javax.swing.JLabel();
        Bkash_Back = new javax.swing.JLabel();
        Pay = new javax.swing.JButton();
        Show = new javax.swing.JLabel();
        Deep_Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AC.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        AC.setForeground(new java.awt.Color(255, 255, 255));
        AC.setText("Mobile  No    :");
        getContentPane().add(AC, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, 24));

        Pass.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        Pass.setForeground(new java.awt.Color(255, 255, 255));
        Pass.setText(" Password      :");
        getContentPane().add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, 22));

        amount.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        amount.setForeground(new java.awt.Color(255, 255, 255));
        amount.setText("Enter Amount   :");
        getContentPane().add(amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 250, 110, 24));
        getContentPane().add(Acc, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 208, 31));
        getContentPane().add(tk, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 208, 32));

        pword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwordActionPerformed(evt);
            }
        });
        getContentPane().add(pword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 208, 34));

        Light_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Light_Back.jpg"))); // NOI18N
        getContentPane().add(Light_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 400, 180));
        getContentPane().add(Bkash_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 230, 50));

        Pay.setBackground(new java.awt.Color(153, 255, 255));
        Pay.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        Pay.setText("FINISH AND PAY");
        Pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayActionPerformed(evt);
            }
        });
        getContentPane().add(Pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 250, 40));

        Show.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        Show.setForeground(new java.awt.Color(153, 255, 255));
        getContentPane().add(Show, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 220, 40));

        Deep_Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Deep_Back.jpg"))); // NOI18N
        getContentPane().add(Deep_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwordActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_pwordActionPerformed

    private void PayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayActionPerformed
        String M_num = Acc.getText();
        if (M_num.isEmpty() || pword.getText().isEmpty())
            JOptionPane.showMessageDialog(rootPane, "Mobile No and Password can not be empty");
        /*else if(!M_num.isEmpty()){
            int sz=M_num.length();
            if(sz<11)JOptionPane.showMessageDialog(rootPane,"Mobile_no is incorrect");
        }*/
        else if (tk.getText().isEmpty())
            JOptionPane.showMessageDialog(rootPane, "Enter The Required Amount");
        else if (!tk.getText().equals(total))
            JOptionPane.showMessageDialog(rootPane, "Enter Correct Amount");
        else {
            JOptionPane.showMessageDialog(rootPane, "Payment Completed !!!");
            try {
                String ss = String.valueOf(Nseat);
                String query = "";

                if (userExists(USERID, busname) == true) {
                    Nseat += prevSeats;
                    ss = String.valueOf(Nseat);
                    query = "UPDATE my_booking SET seatBooked = '"+ss+"' FWHERE user = '"+USERID+"';";
                } else {
                    query = "INSERT INTO my_booking VALUES('" + busname + "','" + ss + "','" + date + "','" + from + "','"
                            + to + "','" + dtime + "','" + atime + "','" + USERID + "');";
                }
                stmt.executeUpdate(query);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, ex, "Database Error!", 0);
                Logger.getLogger(Complain_Box_User.class.getName()).log(Level.SEVERE, null, ex);
            }
            setVisible(false);
            //new Ticket(name,contact,from,to,date,dtime,seat,total,busname,USERID).setVisible(true);
            new Ticket(name, contact, from, to, busname, date, dtime, atime, seat, total, USERID).setVisible(true);
        }
    }//GEN-LAST:event_PayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AC;
    private javax.swing.JTextField Acc;
    private javax.swing.JLabel Bkash_Back;
    private javax.swing.JLabel Deep_Back;
    private javax.swing.JLabel Light_Back;
    private javax.swing.JLabel Pass;
    private javax.swing.JButton Pay;
    private javax.swing.JLabel Show;
    private javax.swing.JLabel amount;
    private javax.swing.JPasswordField pword;
    private javax.swing.JTextField tk;
    // End of variables declaration//GEN-END:variables
}
