
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;

public class Ticket extends javax.swing.JFrame {

    String USERID;

    public Ticket() {
        initComponents();
        setResizable(false);
    }

    public Ticket(String name, String contact, String from, String to, String busname, String date, String dtime, String atime, String seat, String total, String userid) {
        initComponents();
        setResizable(false);
        name1.setText(name);
        name2.setText(name);
        contact1.setText(contact);
        contact2.setText(contact);
        from1.setText(from);
        from2.setText(from);
        to1.setText(to);
        to2.setText(to);
        busname1.setText(busname);
        busname2.setText(busname);
        date1.setText(date);
        date2.setText(date);
        atime1.setText(atime);
        atime2.setText(atime);
        dtime1.setText(dtime);
        dtime2.setText(dtime);
        seat1.setText(seat);
        seat2.setText(seat);
        total1.setText(total);
        total2.setText(total);
        USERID = userid;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        from1 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        dtime1 = new javax.swing.JLabel();
        seat1 = new javax.swing.JLabel();
        contact1 = new javax.swing.JLabel();
        to1 = new javax.swing.JLabel();
        busname1 = new javax.swing.JLabel();
        atime1 = new javax.swing.JLabel();
        total1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        from2 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        dtime2 = new javax.swing.JLabel();
        seat2 = new javax.swing.JLabel();
        contact2 = new javax.swing.JLabel();
        to2 = new javax.swing.JLabel();
        busname2 = new javax.swing.JLabel();
        atime2 = new javax.swing.JLabel();
        total2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        jLabel2.setText("BusMania");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        jLabel4.setText("BusMania");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 48, 421, 10));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText(".");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 6, 11, 14));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText(".");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 44, 11, 14));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText(".");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 24, 11, 14));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText(".");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 65, 11, 14));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText(".");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 86, 11, 14));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText(".");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 107, 11, 14));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText(".");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 128, 11, 14));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText(".");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 149, 11, 14));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText(".");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 170, 11, 14));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText(".");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 191, 11, 14));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText(".");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 212, 11, 14));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText(".");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 233, 11, 14));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText(".");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 254, 11, 14));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText(".");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 274, 11, 14));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText(".");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 294, 11, 14));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 48, 240, 10));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("Contact");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 64, -1, -1));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("To");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 106, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Bus Name");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Arrival");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 190, -1, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel36.setText("Total");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 240, -1, -1));

        jLabel38.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel38.setText("---Thanks for choosing BusMania---");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 297, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setText("Seat");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 240, -1, -1));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Departure");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 190, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Date");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 148, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("From");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 106, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Name");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 64, -1, -1));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Name:");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 64, -1, -1));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Contact:");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 64, -1, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("From:");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 106, -1, -1));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setText("To:");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 106, -1, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Date:");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 148, -1, -1));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel33.setText("Bus Name:");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 148, -1, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel35.setText("Departure");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel37.setText("Arrival");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 190, -1, -1));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel39.setText("Total:");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 232, -1, -1));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setText("Seat");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 232, -1, -1));

        jLabel41.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        jLabel41.setText("---Thanks for choosing BusMania---");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 297, -1, -1));
        jPanel1.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 240, 20));
        jPanel1.add(from1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 200, 20));
        jPanel1.add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 210, 20));
        jPanel1.add(dtime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 100, 20));
        jPanel1.add(seat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 170, 20));
        jPanel1.add(contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 150, 20));
        jPanel1.add(to1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 150, 20));
        jPanel1.add(busname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 140, 20));
        jPanel1.add(atime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 140, 20));
        jPanel1.add(total1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 140, 30));
        jPanel1.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 130, 20));
        jPanel1.add(from2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 110, 20));
        jPanel1.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, 120, 20));
        jPanel1.add(dtime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 120, 20));
        jPanel1.add(seat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 120, 20));
        jPanel1.add(contact2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 100, 20));
        jPanel1.add(to2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 100, 20));
        jPanel1.add(busname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 100, 20));
        jPanel1.add(atime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 100, 20));
        jPanel1.add(total2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 100, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ticketback.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 338, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 338, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/gold-background-1495823768nPS.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 700, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");

        job.setPrintable((Graphics pg, PageFormat pf, int pageNum) -> {
            pf.setOrientation(PageFormat.LANDSCAPE);
            if (pageNum > 0) {
                return Printable.NO_SUCH_PAGE;
            }

            Graphics2D g2 = (Graphics2D) pg;
            g2.translate(pf.getImageableX(), pf.getImageableY());
            g2.scale(0.47, 0.47);

            jPanel1.print(g2);

            return Printable.PAGE_EXISTS;
        });
        boolean ok = job.printDialog();
        if (ok) {
            try {

                job.print();
            } catch (PrinterException ex) {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TicketBooking tk = new TicketBooking(USERID);
        tk.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ticket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atime1;
    private javax.swing.JLabel atime2;
    private javax.swing.JLabel busname1;
    private javax.swing.JLabel busname2;
    private javax.swing.JLabel contact1;
    private javax.swing.JLabel contact2;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel dtime1;
    private javax.swing.JLabel dtime2;
    private javax.swing.JLabel from1;
    private javax.swing.JLabel from2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel seat1;
    private javax.swing.JLabel seat2;
    private javax.swing.JLabel to1;
    private javax.swing.JLabel to2;
    private javax.swing.JLabel total1;
    private javax.swing.JLabel total2;
    // End of variables declaration//GEN-END:variables
}
