
import java.sql.*;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public final class User_Login extends javax.swing.JFrame {

    String url = "jdbc:mysql://localhost:3306/busmania";
    String username = "root";
    String pass = "admin";

    public User_Login() {
        setResizable(false);
        initComponents();
        ScaleImage1();
        ScaleImage2();
        ScaleImage3();
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
    }

    public void ScaleImage1() {
        ImageIcon ic;
        ic = new ImageIcon("D:\\Java\\BusMania\\src\\img\\user icon.png");
        Image im = ic.getImage();
        Image imScale = im.getScaledInstance(label1.getWidth(), label1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledicon = new ImageIcon(imScale);
        label1.setIcon(scaledicon);
    }

    public void ScaleImage2() {
        ImageIcon ic;
        ic = new ImageIcon("D:\\Java\\BusMania\\src\\img\\password icon.png");
        Image im = ic.getImage();
        Image imScale = im.getScaledInstance(label2.getWidth(), label2.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledicon = new ImageIcon(imScale);
        label2.setIcon(scaledicon);
    }

    public void ScaleImage3() {
        ImageIcon ic;
        ic = new ImageIcon("D:\\Java\\BusMania\\src\\img\\user.jpg");
        Image im = ic.getImage();
        Image imScale = im.getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon scaledicon = new ImageIcon(imScale);
        jLabel1.setIcon(scaledicon);
    }

    public void SigninActionPerformed_Work() {
        String USERID = user_id.getText();
        String PASS = user_pass.getText();
        if (USERID.isEmpty() || PASS.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username or password cannot be empty!", "Error", 2);
        } else {
            try {
                String query = "SELECT * FROM users WHERE user_id = '" + USERID + "' AND password = '" + PASS + "';";
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = (Connection) DriverManager.getConnection(url, username, pass); //2
                Statement st = (Statement) con.createStatement();
                ResultSet rs = st.executeQuery(query);

                if (rs.next()) {
                    TicketBooking tb = new TicketBooking(USERID);
                    tb.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Wrong user id or password!\nTry again!", "Alert", 0);
                }

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "Wrong user id or password!\nTry again!", "Alert", 0);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        user_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        signin_button = new javax.swing.JButton();
        create_account_button = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        user_pass = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user_id.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        user_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_idActionPerformed(evt);
            }
        });
        getContentPane().add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 460, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Haettenschweiler", 1, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("USER LOGIN");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 690, 60));

        signin_button.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        signin_button.setText("Sign In");
        signin_button.setPreferredSize(new java.awt.Dimension(90, 30));
        signin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(signin_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 200, 40));

        create_account_button.setBackground(new java.awt.Color(204, 255, 255));
        create_account_button.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        create_account_button.setForeground(new java.awt.Color(255, 0, 0));
        create_account_button.setText(">>No account? Create One!!");
        create_account_button.setPreferredSize(new java.awt.Dimension(90, 30));
        create_account_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_account_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(create_account_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 260, 30));

        exit_button.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        exit_button.setText("EXIT");
        exit_button.setPreferredSize(new java.awt.Dimension(90, 30));
        exit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(exit_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, 90, -1));
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 40, 30));
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 40, 30));

        Back.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Back.setText("Developer info");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        user_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                user_passKeyPressed(evt);
            }
        });
        getContentPane().add(user_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 198, 460, 30));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 820, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void user_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_idActionPerformed

    private void signin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_buttonActionPerformed
        // TODO add your handling code here:
        SigninActionPerformed_Work();

    }//GEN-LAST:event_signin_buttonActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Developer_Info di = new Developer_Info();
        di.setVisible(true);
        dispose();

    }//GEN-LAST:event_BackActionPerformed

    private void create_account_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_account_buttonActionPerformed
        // TODO add your handling code here:
        Create_Account CA = new Create_Account();
        dispose();
        CA.setVisible(true);

    }//GEN-LAST:event_create_account_buttonActionPerformed

    private void exit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exit_buttonActionPerformed

    private void user_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_passKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            SigninActionPerformed_Work();
        }

    }//GEN-LAST:event_user_passKeyPressed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        User_Login log = new User_Login();
        log.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton create_account_button;
    private javax.swing.JButton exit_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JButton signin_button;
    private javax.swing.JTextField user_id;
    private javax.swing.JPasswordField user_pass;
    // End of variables declaration//GEN-END:variables
}
