
public class User_Welcome extends javax.swing.JFrame {

    public User_Welcome() {
        setResizable(false);
        setTitle("Welcome Page");
        initComponents();
        // ScaleImage();
        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
    }

    /*public void ScaleImage(){
        ImageIcon icon;
        icon = new ImageIcon("D:\\Java\\BusMania\\src\\img\\welcome.jpg");
        Image img = icon.getImage();
        Image imgScale = img.getScaledInstance(Background.getWidth(),Background.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon scaledIcon =new ImageIcon(imgScale);
        Background.setIcon(scaledIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        LoadingBar = new javax.swing.JProgressBar();
        loadinglevel = new javax.swing.JLabel();
        loadingvalue = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Welcome Y2", 1, 48)); // NOI18N
        jButton1.setText("Welcome To BusMania");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 38, 607, -1));
        getContentPane().add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 434, 800, 20));

        loadinglevel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadinglevel.setForeground(new java.awt.Color(51, 255, 255));
        loadinglevel.setText("Loading......");
        getContentPane().add(loadinglevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 402, -1, -1));

        loadingvalue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadingvalue.setForeground(new java.awt.Color(0, 255, 255));
        loadingvalue.setText("0 %");
        getContentPane().add(loadingvalue, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 402, 29, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/welcome.jpg"))); // NOI18N
        Background.setToolTipText("Welcome Page");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        User_Welcome wel = new User_Welcome();
        wel.setVisible(true);

        User_Login log = new User_Login();
        try {
            for (int i = 0; i < 100; i++) {
                Thread.sleep(12);
                wel.loadingvalue.setText(i + "%");
                if (i == 10) {
                    wel.loadinglevel.setText("Turning On Modules...");
                }
                if (i == 20) {
                    wel.loadinglevel.setText("Loading Modules...");
                }
                if (i == 50) {
                    wel.loadinglevel.setText("Connecting to Database...");
                }
                if (i == 70) {
                    wel.loadinglevel.setText("Connection Successful!");
                }
                if (i == 80) {
                    wel.loadinglevel.setText("Launching Application...");
                }
                wel.LoadingBar.setValue(i);
            }
        } catch (InterruptedException e) {
        }
        wel.setVisible(false);
        log.setVisible(true);
        wel.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel loadinglevel;
    private javax.swing.JLabel loadingvalue;
    // End of variables declaration//GEN-END:variables
}
