
import java.awt.Color;
import static java.awt.Color.black;
import static java.awt.Color.green;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

public class ViewRoutes extends javax.swing.JFrame {

    String url = "jdbc:mysql://localhost:3306/busmania";
    String username = "root";
    String pass = "admin";

    public ViewRoutes() {
        initComponents();
        setResizable(false);

        Set_Table_Prop();
        Search_Routes();
        showTable();
        Set_Frame();
    }

    public void Set_Frame() {
        getContentPane().setBackground(Color.black);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    public void Set_Table_Prop() {
        JTableHeader tableHeader = jTable1.getTableHeader();
        tableHeader.setForeground(Color.black);

        Font headerFont = new Font("Oswald", Font.PLAIN, 15);
        Font cellFont = new Font("Verdana", Font.PLAIN, 14);
        tableHeader.setFont(headerFont);
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(5).setPreferredWidth(100);
        jTable1.setRowHeight(25);
        jTable1.setBackground(black);
        jTable1.setForeground(green);
        jTable1.setFont(cellFont);
    }

    class route_info {

        public String date, source, destination, busName, arrivalTime, deptTime, ticketFare;

        public route_info(String date, String source, String destination, String busName, String arrivalTime, String deptTime,
                String ticketFare) {
            this.date = date;
            this.source = source;
            this.destination = destination;
            this.busName = busName;
            this.arrivalTime = arrivalTime;
            this.deptTime = deptTime;
            this.ticketFare = ticketFare;
        }
    }

    ArrayList<route_info> routeList = new ArrayList<route_info>();

    public void Search_Routes() {
        try {
            String query = "SELECT * FROM routes;";
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection(url, username, pass); //2
            Statement st = (Statement) con.createStatement();
            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                String source = rs.getString("from_location");
                String destination = rs.getString("to_location");
                query = "SELECT * FROM " + source + "_" + destination + ";";

                Connection con2 = (Connection) DriverManager.getConnection(url, username, pass); //2
                Statement st2 = (Statement) con2.createStatement();
                ResultSet rs2 = st2.executeQuery(query);
                rs2.next();
                route_info obj = new route_info(rs2.getString("date"), source, destination,
                        rs2.getString("bus_name"), rs2.getString("arrival_time"),
                        rs2.getString("departure_time"), rs2.getString("ticket_fare"));

                routeList.add(obj);

            }
            st.close();
            con.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex, url, HEIGHT);
        }
//        System.out.println(routeList.size());
    }

    public void showTable() {
        DefaultTableModel mod = (DefaultTableModel) (jTable1.getModel());
        Object[] col = new Object[7];
        mod.setRowCount(0);
        for (int i = 0; i < routeList.size(); i++) {
            col[0] = routeList.get(i).date;
            col[1] = routeList.get(i).source;
            col[2] = routeList.get(i).destination;
            col[3] = routeList.get(i).busName;
            col[4] = routeList.get(i).arrivalTime;
            col[5] = routeList.get(i).deptTime;
            col[6] = routeList.get(i).ticketFare;
            mod.addRow(col);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Routes");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Source", "Destination", "Bus Name", "Arrival Time", "Departure Time", "Ticket Fare"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 255, 0));
        jButton5.setText("Previous Page");
        jButton5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 5, true));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(329, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Admin_Page ob = new Admin_Page();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRoutes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRoutes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRoutes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRoutes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewRoutes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
